version: "{build}"

skip_tags: false
test: off
max_jobs: 1

install:
  - cmd: IF NOT EXIST i686-8.1.0-release-posix-dwarf-rt_v6-rev0.7z curl -kLO "https://downloads.sourceforge.net/project/mingw-w64/Toolchains%%20targetting%%20Win32/Personal%%20Builds/mingw-builds/8.1.0/threads-posix/dwarf/i686-8.1.0-release-posix-dwarf-rt_v6-rev0.7z"
  - cmd: 7z x i686-8.1.0-release-posix-dwarf-rt_v6-rev0.7z
  - cmd: SET PATH=%APPVEYOR_BUILD_FOLDER%\mingw32\bin;%PATH%
  - cmd: IF NOT EXIST upx-3.96-win32.zip curl -kLO https://github.com/upx/upx/releases/download/v3.96/upx-3.96-win32.zip
  - cmd: 7z x upx-3.96-win32.zip
  - cmd: SET PATH=%APPVEYOR_BUILD_FOLDER%\upx-3.96-win32;%PATH%
  - cmd: SET NAME=%APPVEYOR_PROJECT_NAME%-%APPVEYOR_BUILD_NUMBER%

before_build:
  - cmd: mingw32-make --version | head -1
  - cmd: g++ --version | head -1
  - cmd: 7z --help | head -3
  - cmd: upx --version | head -5

build_script:
  - cmd: mingw32-make -j1 --keep-going release

after_build:
  - cmd: ECHO Deploying "%NAME%.7z".
  - cmd: RENAME deploy %NAME%
  - cmd: 7z a %NAME%.7z %NAME%

cache:
  - i686-8.1.0-release-posix-dwarf-rt_v6-rev0.7z
  - upx-3.96-win32.zip

artifacts:
  - path: $(APPVEYOR_PROJECT_NAME)-$(APPVEYOR_BUILD_NUMBER).7z

deploy:
  - provider: Environment
    name: GH
    on:
      branch: main
      appveyor_repo_tag: true # deploy on tag push only
